// Example of a "relay" - a client and server.
// Uses the old favourite Hello World as a basis.

module ClientAndServer {
    interface Relay {
        string fetch_message();
    };

    struct NoxReading{
       long time;
       long date;
       string station_name;
       long reading_value;
    };

    interface MonitoringStation {
        readonly attribute string station_name;
        readonly attribute string location;
        NoxReading get_reading();
        void activate();
        void deactivate();
        void reset();
    };
};
